In [1]:
import numpy as np
import pandas as pd

In [2]:
array = np.arange(8)

In [3]:
array.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
ar1 = np.ones((5,5))
ar1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.random.randint(5,6)

5

In [6]:
np.random.seed(123)
data = np.random.randn(2,2)

In [7]:
data

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471]])

In [8]:
data * 5

array([[-5.42815302,  4.98672723],
       [ 1.41489249, -7.53147357]])

In [9]:
data + data

array([[-2.17126121,  1.99469089],
       [ 0.565957  , -3.01258943]])

In [10]:
data[:,:] = 1
data

array([[1., 1.],
       [1., 1.]])

In [11]:
data.dtype

dtype('float64')

In [12]:
data

array([[1., 1.],
       [1., 1.]])

In [13]:
data = np.arange(25).reshape(5,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
data.ndim

2

In [15]:
data.shape

(5, 5)

In [16]:
data.dtype

dtype('int32')

In [17]:
data2 = np.zeros((5,5))
data2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
data3 = np.empty((5,5))
data3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
data4 = np.eye(7,6)
data4

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
data5 = np.identity(5)
data5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
data5.dtype

dtype('float64')

In [22]:
data5 = data5.astype(np.int64)

In [23]:
data5.dtype

dtype('int64')

In [24]:
data5

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [25]:
data6 = np.array(['1','2','3'])
data6

array(['1', '2', '3'], dtype='<U1')

In [26]:
data6.dtype

dtype('<U1')

In [27]:
data6.astype(np.float64)

array([1., 2., 3.])

In [28]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
data4

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
data+data4

ValueError: operands could not be broadcast together with shapes (5,5) (7,6) 

In [ ]:
data

In [31]:
data5

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [32]:
data + data5

array([[ 1,  1,  2,  3,  4],
       [ 5,  7,  7,  8,  9],
       [10, 11, 13, 13, 14],
       [15, 16, 17, 19, 19],
       [20, 21, 22, 23, 25]], dtype=int64)

In [33]:
data * data5

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0, 12,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 24]], dtype=int64)

In [34]:
data > data5

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [35]:
data[data > data5]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [36]:
data5[data > data5]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1], dtype=int64)

In [37]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
data[4][4]

24

In [39]:
data[4][4] = 25
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 25]])

In [40]:
data[4,4]

25

In [41]:
arr3d = np.arange(27).reshape(3,3,3) 
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [42]:
arr3d[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [46]:
arr3d[1,1]

array([12, 13, 14])

In [47]:
arr3d[1,1,1]

13

In [48]:
arr3d[:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [49]:
arr3d[:,:2,:1]

array([[[ 0],
        [ 3]],

       [[ 9],
        [12]],

       [[18],
        [21]]])

In [50]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [51]:
arr3d[:,:,:2]

array([[[ 0,  1],
        [ 3,  4],
        [ 6,  7]],

       [[ 9, 10],
        [12, 13],
        [15, 16]],

       [[18, 19],
        [21, 22],
        [24, 25]]])

In [52]:
arr3d[:,:,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [53]:
arr3d[:,0,0]

array([ 0,  9, 18])

In [54]:
arr3d[:,:,0]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [59]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [58]:
data = np.random.randn(7,4)
data

array([[-1.7408125 ,  0.26804298,  0.46098094,  1.95334085],
       [-0.62609821,  0.46100973,  1.06350009,  0.24028396],
       [ 0.22368694, -1.34653359,  0.96119195, -0.02365155],
       [ 2.30516634,  1.24023933, -0.49004091, -0.60109533],
       [-1.28128573, -0.01876862,  1.03726395,  0.49609536],
       [ 1.26590881, -0.59521643,  1.13741213, -0.0573228 ],
       [ 1.27269634, -1.50713513, -0.69024683, -0.68887212]])

In [60]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [61]:
data[names == 'Bob']

array([[-1.7408125 ,  0.26804298,  0.46098094,  1.95334085],
       [ 2.30516634,  1.24023933, -0.49004091, -0.60109533]])

In [63]:
data[names == 'Joe' , 2]

array([ 1.06350009,  1.13741213, -0.69024683])

In [168]:
arr = np.empty((8,4))
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [169]:
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [170]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [171]:
arr[[-3,-7,-5]]

array([[5., 5., 5., 5.],
       [1., 1., 1., 1.],
       [3., 3., 3., 3.]])

In [172]:
data

array([[-1.7408125 , -0.69024683, -0.68887212,  1.03726395],
       [-1.50713513, -0.0573228 ,  0.46098094,  1.06350009],
       [ 6.        ,  6.        ,  6.        ,  6.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [-0.59521643,  0.26804298,  1.13741213,  1.95334085],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 6.        ,  6.        ,  6.        ,  6.        ]])

In [173]:
data[[2,3],[1,2]]

array([6., 5.])

In [174]:
data[2:4] = 5

In [175]:
data

array([[-1.7408125 , -0.69024683, -0.68887212,  1.03726395],
       [-1.50713513, -0.0573228 ,  0.46098094,  1.06350009],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [-0.59521643,  0.26804298,  1.13741213,  1.95334085],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 6.        ,  6.        ,  6.        ,  6.        ]])

In [176]:
data[2] = 6

In [177]:
data

array([[-1.7408125 , -0.69024683, -0.68887212,  1.03726395],
       [-1.50713513, -0.0573228 ,  0.46098094,  1.06350009],
       [ 6.        ,  6.        ,  6.        ,  6.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [-0.59521643,  0.26804298,  1.13741213,  1.95334085],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 6.        ,  6.        ,  6.        ,  6.        ]])

In [178]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [179]:
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [180]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [181]:
np.dot(arr.T,arr)

array([[140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.]])

In [182]:
np.where(arr > 5, 10, arr)

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [183]:
arr.mean()

3.5

In [184]:
arr.mean(axis=1) # rowwisw

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [185]:
arr.mean(axis=0)   # columnwise

array([3.5, 3.5, 3.5, 3.5])

In [186]:
data

array([[-1.7408125 , -0.69024683, -0.68887212,  1.03726395],
       [-1.50713513, -0.0573228 ,  0.46098094,  1.06350009],
       [ 6.        ,  6.        ,  6.        ,  6.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [-0.59521643,  0.26804298,  1.13741213,  1.95334085],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 6.        ,  6.        ,  6.        ,  6.        ]])

In [187]:
data.sort(-1)
data

array([[-1.7408125 , -0.69024683, -0.68887212,  1.03726395],
       [-1.50713513, -0.0573228 ,  0.46098094,  1.06350009],
       [ 6.        ,  6.        ,  6.        ,  6.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [-0.59521643,  0.26804298,  1.13741213,  1.95334085],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 6.        ,  6.        ,  6.        ,  6.        ]])

In [188]:
data

array([[-1.7408125 , -0.69024683, -0.68887212,  1.03726395],
       [-1.50713513, -0.0573228 ,  0.46098094,  1.06350009],
       [ 6.        ,  6.        ,  6.        ,  6.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [-0.59521643,  0.26804298,  1.13741213,  1.95334085],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 6.        ,  6.        ,  6.        ,  6.        ]])

In [189]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [190]:
np.unique(arr)

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [191]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [192]:
arr = np.arange(15)
arr.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [194]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [195]:
arr = np.empty((8,4))
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [196]:
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [199]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [200]:
data

array([[-1.7408125 , -0.69024683, -0.68887212,  1.03726395],
       [-1.50713513, -0.0573228 ,  0.46098094,  1.06350009],
       [ 6.        ,  6.        ,  6.        ,  6.        ],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [-0.59521643,  0.26804298,  1.13741213,  1.95334085],
       [ 5.        ,  5.        ,  5.        ,  5.        ],
       [ 6.        ,  6.        ,  6.        ,  6.        ]])

In [206]:
arr2 = np.arange(32).reshape(8,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [207]:
arr + arr2

array([[ 0.,  1.,  2.,  3.],
       [ 5.,  6.,  7.,  8.],
       [10., 11., 12., 13.],
       [15., 16., 17., 18.],
       [20., 21., 22., 23.],
       [25., 26., 27., 28.],
       [30., 31., 32., 33.],
       [35., 36., 37., 38.]])

In [209]:
np.concatenate([arr, arr2], axis=0)

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.],
       [ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.],
       [24., 25., 26., 27.],
       [28., 29., 30., 31.]])

In [210]:
np.concatenate([arr, arr2], axis=1)

array([[ 0.,  0.,  0.,  0.,  0.,  1.,  2.,  3.],
       [ 1.,  1.,  1.,  1.,  4.,  5.,  6.,  7.],
       [ 2.,  2.,  2.,  2.,  8.,  9., 10., 11.],
       [ 3.,  3.,  3.,  3., 12., 13., 14., 15.],
       [ 4.,  4.,  4.,  4., 16., 17., 18., 19.],
       [ 5.,  5.,  5.,  5., 20., 21., 22., 23.],
       [ 6.,  6.,  6.,  6., 24., 25., 26., 27.],
       [ 7.,  7.,  7.,  7., 28., 29., 30., 31.]])