In [3]:
import numpy as np
import pandas as pd

In [14]:
array = np.arange(8)

In [15]:
array.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [86]:
ar1 = np.ones((5,5))
ar1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
np.random.randint(5,6)

5

In [73]:
np.random.seed(123)
data = np.random.randn(2,2)

In [75]:
data

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471]])

In [76]:
data * 5

array([[-5.42815302,  4.98672723],
       [ 1.41489249, -7.53147357]])

In [77]:
data + data

array([[-2.17126121,  1.99469089],
       [ 0.565957  , -3.01258943]])

In [78]:
data[:,:] = 1
data

array([[1., 1.],
       [1., 1.]])

In [79]:
data.dtype

dtype('float64')

In [80]:
data

array([[1., 1.],
       [1., 1.]])

In [82]:
data = np.arange(25).reshape(5,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
data.ndim

2

In [84]:
data.shape

(5, 5)

In [85]:
data.dtype

dtype('int32')

In [87]:
data2 = np.zeros((5,5))
data2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [88]:
data3 = np.empty((5,5))
data3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [98]:
data4 = np.eye(7,6)
data4

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [114]:
data5 = np.identity(5)
data5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [115]:
data5.dtype

dtype('float64')

In [127]:
data5 = data5.astype(np.int64)

In [128]:
data5.dtype

dtype('int64')

In [125]:
data5

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [138]:
data6 = np.array(['1','2','3'])
data6

array(['1', '2', '3'], dtype='<U1')

In [139]:
data6.dtype

dtype('<U1')

In [140]:
data6.astype(np.float64)

array([1., 2., 3.])

In [141]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [144]:
data4

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [145]:
data+data4

ValueError: operands could not be broadcast together with shapes (5,5) (7,6) 

In [146]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [147]:
data5

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [148]:
data + data5

array([[ 1,  1,  2,  3,  4],
       [ 5,  7,  7,  8,  9],
       [10, 11, 13, 13, 14],
       [15, 16, 17, 19, 19],
       [20, 21, 22, 23, 25]], dtype=int64)

In [149]:
data * data5

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0, 12,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 24]], dtype=int64)

In [152]:
data > data5

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [157]:
data[data > data5]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [158]:
data5[data > data5]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1], dtype=int64)

In [159]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [160]:
data[4][4]

24

In [162]:
data[4][4] = 25
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 25]])

In [163]:
data[4,4]

25

In [168]:
arr3d = np.arange(27).reshape(3,3,3) 
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [172]:
arr3d[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [173]:
arr3d[1,1]

array([12, 13, 14])

In [174]:
arr3d[1,1,1]

13

In [175]:
arr3d[:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [177]:
arr3d[:,:2,:1]

array([[[ 0],
        [ 3]],

       [[ 9],
        [12]],

       [[18],
        [21]]])

In [178]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [179]:
arr3d[:,:,:2]

array([[[ 0,  1],
        [ 3,  4],
        [ 6,  7]],

       [[ 9, 10],
        [12, 13],
        [15, 16]],

       [[18, 19],
        [21, 22],
        [24, 25]]])

In [180]:
arr3d[:,:,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [181]:
arr3d[:,0,0]

array([ 0,  9, 18])

In [182]:
arr3d[:,:,0]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])