In [1]:
my_arr = list(range(1000000))

In [6]:
%time for _ in range(10): my_arr2 = [x * 2 for x in my_arr]

Wall time: 1.07 s


In [7]:
import numpy as np
num_arr = np.arange(1000000)

In [8]:
%time for _ in range(10): num_arr2 = num_arr * 2

Wall time: 36 ms


In [9]:
zeroes_arr = np.zeros(10)

In [10]:
zeroes_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
two_d_arr = np.zeros((4,3))

In [14]:
two_d_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
two_d_arr.reshape((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
ones_arr = np.ones((3,4))

In [18]:
ones_arr = ones_arr * 5

In [19]:
ones_arr

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [22]:
arr = np.array([1,2,3,4,5,6,7,8])

In [24]:
arr_res = arr.reshape((2,4))

In [25]:
arr_res

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr_res[1,3]

8

In [27]:
arr_res[0,2]

3

In [29]:
arr_res[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [32]:
arr_2d = np.arange(0,101,5)

In [33]:
arr_2d

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [34]:
emp_arr = np.empty((3,3))

In [35]:
emp_arr

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.68771711e-321],
       [1.23075756e-312, 1.97345609e-312, 8.01089061e-307]])

In [37]:
emp_arr.shape

(3, 3)

In [38]:
emp_arr.dtype

dtype('float64')

In [39]:
emp_arr.ndim

2

In [47]:
arr = np.ones((10,10))

In [48]:
arr[1:-1,1:-1] = 0

In [49]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [53]:
arr=np.ones((5,5))
arr[1:-1:2]=0


In [54]:
arr

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [ ]:
array[rows,columns]

In [83]:
arr = np.zeros((8,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [84]:
arr[::2,::2]=1 #for even
arr[1::2,1::2] = 1 #for odd

In [85]:
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [64]:
arr.dtype

dtype('float64')

In [68]:
arr.astype("int8")

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int8)

In [70]:
arr1 = np.array([1,2,3,4]) 
arr2 = np.array([5,6,7,8])
add_arr = arr1 + arr2

In [71]:
add_arr

array([ 6,  8, 10, 12])

In [74]:
dir(np.amin)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__wrapped__',
 '_implementation']

In [75]:
arr1

array([1, 2, 3, 4])

In [77]:
arr1>3

array([False, False, False,  True])

In [78]:
arr1[arr1>3]

array([4])

In [79]:
arr1.astype("float64")

array([1., 2., 3., 4.])

In [87]:
arr1[[0,2]]

array([1, 3])

In [88]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [89]:
np.max(arr1)

4

In [90]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [91]:
np.argmax(arr1)

3

In [92]:
arr1

array([1, 2, 3, 4])

In [93]:
marks = np.array([30, 80 , 60 ,90 , 10])

In [94]:
result = np.where(marks>33 , "Pass" , "Fail")

In [95]:
result

array(['Fail', 'Pass', 'Pass', 'Pass', 'Fail'], dtype='<U4')

In [101]:
array1 = np.arange(1,11).reshape((2,5))
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [102]:
array1.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [103]:
array1.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [104]:
array1.mean()

5.5

In [107]:
array1.mean(axis = 0)

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [106]:
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [108]:
array1.mean(axis=1)

array([3., 8.])

In [110]:
arr1.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [111]:
arr1

array([1, 2, 3, 4])

In [112]:
arr1.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

In [113]:
marks

array([30, 80, 60, 90, 10])

In [114]:
marks>33

array([False,  True,  True,  True, False])

In [115]:
(marks>33).sum()

3

In [116]:
(marks>33).any()

True

In [117]:
(marks>33).all()

False

In [134]:
arr1 = np.array([5,7,3,1])
np.sort(arr1)

array([1, 3, 5, 7])

In [130]:
arr1

array([1, 2, 3, 4])

In [135]:
arr2 = np.array([5,7,5,3,7,1])
np.unique(arr2)

array([1, 3, 5, 7])

In [136]:
d2_arr = np.array([[1,5],[3,7]])

In [137]:
d2_arr

array([[1, 5],
       [3, 7]])

In [138]:
d2_arr.trace()

8

In [147]:
from numpy import linalg
linalg.eig(d2_arr)

(array([-0.89897949,  8.89897949]), array([[-0.93484692, -0.53484692],
        [ 0.35505103, -0.84494897]]))

In [151]:
np.random.normal((2,2))

array([1.36780622, 2.92820814])

In [152]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [154]:
np.concatenate([arr1,arr2] , axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [155]:
arr1

array([[1, 2],
       [3, 4]])

In [156]:
arr2

array([[5, 6],
       [7, 8]])

In [157]:
np.concatenate([arr1,arr2] , axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [158]:
np.hstack([arr1 , arr2])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [159]:
np.vstack([arr1 , arr2])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [160]:
np.r_[arr1,arr2]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [161]:
np.c_[arr1,arr2]

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])